server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Reference the environment variable injected by Docker
jwt:
  secret: ${JWT_SECRET}